// <auto-generated />
namespace I4PRJ_SmartStorage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MergeInit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MergeInit));
        
        string IMigrationMetadata.Id
        {
            get { return "201611241253038_MergeInit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
