// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace SmartStorage.DAL.Migrations
{
  [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201612060333262_InitDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
