//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseEngineered
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public int StatusId { get; set; }
        public int InventoryId { get; set; }
        public int ProductId { get; set; }
        public double ExpQuantity { get; set; }
        public double CurQuantity { get; set; }
        public double Difference { get; set; }
        public System.DateTime Updated { get; set; }
        public string ByUser { get; set; }
        public bool IsStarted { get; set; }
    
        public virtual Inventories Inventories { get; set; }
        public virtual Products Products { get; set; }
    }
}
